// Panel styles, extracted from ChatPanel in Lot 2 (structure split): the
// sheet/dialog components live in their own files and share this factory.
import {StyleSheet} from 'react-native';


// Styles are a FUNCTION of the user's text/button scale (Appearance settings):
// every fontSize follows `scale`, every interactive button/chip padding
// follows `btnScale`. Layout paddings stay fixed. Built once per scale change
// via useMemo in the component. (Inline scaled styles at render sites REPLACE
// these, so there is never any double-scaling.)
export const makeStyles = (scale: number, btnScale: number) =>
  StyleSheet.create({
  root: {flex: 1, backgroundColor: '#ffffff'},
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 8,
    paddingRight: 2,
    paddingVertical: 7,
    backgroundColor: '#000000',
  },
  handle: {fontSize: 18 * scale, color: '#ffffff', paddingHorizontal: 2},
  headerBrain: {flex: 1, marginHorizontal: 6},
  headerBrainText: {color: '#ffffff', fontSize: 14 * scale, fontWeight: '700'},
  // v0.64 (user): the icons SPREAD over the available width — bigger
  // gaps, fewer accidental neighbours on e-ink.
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1.4,
    justifyContent: 'space-evenly',
    marginLeft: 6,
  },
  headerSep: {width: 4},
  libLink: {color: '#ffffff', fontSize: 12 * scale, fontWeight: '700'},
  // v0.78 BrainBar + ContextTray (IA cleanup).
  brainTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#dddddd',
    marginBottom: 4,
  },
  brainMeta: {fontSize: 11 * scale, color: '#555555'},
  brainTopBtn: {
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 7,
    paddingHorizontal: 9 * btnScale,
    paddingVertical: 5 * btnScale,
  },
  brainTopBtnText: {fontSize: 12 * scale, color: '#000000', fontWeight: '600'},
  // inline dropdown (brain list / ⋯ overflow) — matches the spec mockup.
  dropdown: {
    borderBottomWidth: 1,
    borderBottomColor: '#000000',
    backgroundColor: '#ffffff',
    paddingVertical: 4,
  },
  dropItem: {paddingHorizontal: 16 * btnScale, paddingVertical: 9 * btnScale},
  dropItemText: {fontSize: 14 * scale, color: '#333333'},
  dropItemTextOn: {color: '#000000', fontWeight: '700'},
  dropUsage: {
    fontSize: 10 * scale,
    color: '#777777',
    fontFamily: 'monospace',
    paddingHorizontal: 16,
    paddingTop: 2,
  },
  ctxTray: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    // v0.79.7: a line under the context zone so it reads as its own band.
    borderBottomWidth: 1,
    borderBottomColor: '#dddddd',
  },
  // v0.80.1 (user): the tray announces itself.
  ctxTrayLabel: {fontSize: 12 * scale, fontWeight: '700', color: '#000000'},
  dim: {fontSize: 11 * scale, color: '#555555'},
  // ▾ snaps popover (v0.54: header 9 → 5 icons).
  snapTrigger: {flexDirection: 'row', alignItems: 'center'},
  snapCaret: {color: '#ffffff', fontSize: 10 * scale, marginLeft: 1},
  snapPopover: {
    position: 'absolute',
    top: 36,
    right: 40,
    zIndex: 30,
    elevation: 6,
    flexDirection: 'row',
    backgroundColor: '#000000',
    borderWidth: 1,
    borderColor: '#ffffff',
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  offlineBanner: {
    fontSize: 11 * scale,
    color: '#000000',
    fontWeight: '700',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#000000',
    backgroundColor: '#e8e8e8',
  },
  provRow: {flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 2},
  provChip: {
    borderWidth: 1.5,
    borderColor: '#000000',
    borderRadius: 8,
    paddingHorizontal: 12 * btnScale,
    paddingVertical: 7 * btnScale,
    backgroundColor: '#ffffff',
  },
  provChipText: {fontSize: 13 * scale, fontWeight: '700', color: '#000000'},
  sheetWrap: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
  },
  sheet: {
    alignSelf: 'stretch',
    flex: 1,
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#000000',
    borderRadius: 14,
    padding: 10,
  },
  sheetHead: {flexDirection: 'row', alignItems: 'center'},
  sheetTitle: {flex: 1, fontSize: 13 * scale, fontWeight: '700', color: '#000000'},
  sheetClose: {padding: 6 * btnScale},
  sheetCloseText: {fontSize: 16 * scale, color: '#000000'},
  voletSrcRow: {flexDirection: 'row', alignItems: 'center', gap: 8},
  flexOne: {flex: 1},
  voletLibLink: {
    fontSize: 12,
    fontWeight: '600',
    textDecorationLine: 'underline',
    color: '#000000',
  },
  sheetSrc: {fontSize: 11 * scale, color: '#555555', marginTop: 2, marginBottom: 6},
  sheetBody: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#000000',
    padding: 8,
    backgroundColor: '#fafafa',
  },
  sheetBtns: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 10,
    flexWrap: 'wrap',
  },
  actBtn2: {
    borderWidth: 1.5,
    borderColor: '#000000',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12 * btnScale,
    paddingVertical: 8 * btnScale,
  },
  actBtn2Text: {fontSize: 12 * scale, fontWeight: '600', color: '#000000'},
  actBtnDark: {backgroundColor: '#000000'},
  dialog: {
    alignSelf: 'stretch',
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#000000',
    padding: 14,
    // v0.80.0 (audit H1): a dialog can NEVER outgrow the panel — a long
    // "Added pages" list used to push ✕ and the buttons off-screen and
    // lock the sheet (the same failure the removed "＋ Whole note" hit).
    maxHeight: '92%',
  },
  dialogText: {fontSize: 13 * scale, color: '#000000', lineHeight: 19},
  sheetEdit: {textAlignVertical: 'top', color: '#000000'},
  histRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#dddddd',
  },
  histMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    gap: 8,
  },
  histTitle: {flex: 1, fontSize: 13 * scale, color: '#000000'},
  histDate: {fontSize: 11 * scale, color: '#555555', fontVariant: ['tabular-nums']},
  histDel: {paddingHorizontal: 10 * btnScale, paddingVertical: 10 * btnScale},
  histDelText: {fontSize: 13 * scale, color: '#000000', fontWeight: '600'},
  // The ONE context line (v0.54).
  ctxState: {fontSize: 11 * scale, color: '#000000', fontWeight: '600', marginTop: 1},
  ctxSheetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  ctxAddedList: {marginTop: 10, gap: 4},
  // v0.80.0 (audit H1): hard cap so a 100-page add can't outgrow the sheet.
  lassoPreview: {
    width: '100%',
    height: 280,
    borderWidth: 1,
    borderColor: '#888888',
    borderRadius: 8,
    marginVertical: 6,
  },
  ctxAddedScroll: {maxHeight: 180},
  ctxAddedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  ctxAddedDel: {fontSize: 13 * scale, color: '#000000', fontWeight: '600'},
  ctxDropBtn: {
    marginTop: 8,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 7,
    paddingHorizontal: 10 * btnScale,
    paddingVertical: 6 * btnScale,
  },
  ctxDropBtnText: {fontSize: 12 * scale, color: '#000000', fontWeight: '600'},
  // v0.55 start card (empty conversation): pick who you talk to.
  // v0.74 Stage 2 — the compact gate row + its "Agent ▾" submenu.
  actBtnBusy: {backgroundColor: '#000000'},
  actBtnOff: {borderColor: '#999999', opacity: 0.5},
  offWarn: {fontSize: 12.5 * scale, color: '#000000', fontStyle: 'italic', marginTop: 6},
  ctxChip: {
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 999,
    paddingHorizontal: 11 * btnScale,
    paddingVertical: 5 * btnScale,
  },
  ctxAddChip: {borderStyle: 'dashed', borderColor: '#555555'},
  ctxChipOn: {backgroundColor: '#000000'},
  ctxChipText: {fontSize: 12 * scale, color: '#000000'},
  ctxChipTextOn: {color: '#ffffff'},
  // "Added from search" section title (context sheet).
  ctxAdded: {fontSize: 11 * scale, fontWeight: '600', color: '#000000'},
  rangeInputs: {flexDirection: 'row', alignItems: 'center', gap: 4},
  rangeInput: {
    borderWidth: 1,
    borderColor: '#000000',
    width: 44,
    paddingHorizontal: 4,
    paddingVertical: 3,
    fontSize: 12 * scale,
    color: '#000000',
    textAlign: 'center',
  },
  chat: {flex: 1},
  chatContent: {padding: 12},
  hint: {color: '#777777', fontStyle: 'italic', marginVertical: 6},
  bubble: {
    marginVertical: 4,
    padding: 9,
    borderWidth: 1,
    borderColor: '#000000',
  },
  bubbleUser: {
    backgroundColor: '#f4f4f4',
    alignSelf: 'flex-end',
    maxWidth: '88%',
  },
  bubbleAI: {
    backgroundColor: '#ffffff',
    alignSelf: 'flex-start',
    maxWidth: '95%',
  },
  bubbleText: {color: '#000000'},
  copyRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 6,
    marginTop: 6,
  },
  copyBtn: {
    borderWidth: 1,
    borderColor: '#000000',
    paddingHorizontal: 10 * btnScale,
    paddingVertical: 4 * btnScale,
  },
  copyText: {fontSize: 11 * scale, color: '#000000'},
  // 🌐 badge (2026-08-16): a REAL web_search ran for this answer — its
  // absence means the text (sources included) came from the model's memory.
  webBadge: {fontSize: 10 * scale, color: '#555555', marginBottom: 2},
  busyBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 5,
    backgroundColor: '#f0f0f0',
  },
  busyText: {flex: 1, fontSize: 12 * scale, color: '#000000', fontWeight: '600'},
  stopBtn: {
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 7,
    paddingHorizontal: 10 * btnScale,
    paddingVertical: 3 * btnScale,
    backgroundColor: '#ffffff',
  },
  stopBtnText: {fontSize: 12 * scale, fontWeight: '700', color: '#000000'},
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: 8,
    borderTopWidth: 1,
    borderTopColor: '#000000',
    gap: 6,
  },
  // v0.77: inline quick-action chips under the field (replaces the ⚡ sheet).
  qaInline: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    paddingHorizontal: 8,
    paddingBottom: 8,
  },
  qaChip: {
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 999,
    backgroundColor: '#ffffff',
  },
  qaChipHot: {backgroundColor: '#000000'},
  qaChipText: {color: '#000000', fontWeight: '600'},
  qaChipTextHot: {color: '#ffffff'},
  emptyState: {paddingVertical: 24, paddingHorizontal: 16, alignItems: 'center'},
  // v0.80.1 (device 2026-07-26): the input field and the M button follow
  // the Button-size setting like their Paste/Web neighbours — their fixed
  // paddings/logo left them visibly shorter at L/XL.
  chatInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 8,
    paddingHorizontal: 8 * btnScale,
    paddingVertical: 9 * btnScale,
    color: '#000000',
    maxHeight: 110 * scale,
  },
  sendBtn: {
    backgroundColor: '#000000',
    borderRadius: 9,
    paddingHorizontal: 16 * btnScale,
    paddingVertical: 10 * btnScale,
  },
  sendBtnOff: {backgroundColor: '#999999'},
  sendText: {color: '#ffffff', fontSize: 18 * scale},
  sendLogo: {width: 20 * btnScale, height: 20 * btnScale},
  // One-shot connector chips (v0.50): compact, in the input row.
  oneShot: {
    borderWidth: 1.5,
    borderColor: '#000000',
    borderRadius: 9,
    paddingHorizontal: 9 * btnScale,
    paddingVertical: 10 * btnScale,
  },
  oneShotOn: {backgroundColor: '#000000'},
  oneShotOff: {borderColor: '#999999', opacity: 0.5},
  oneShotText: {fontSize: 13 * scale, fontWeight: '600', color: '#000000'},
  oneShotTextOn: {color: '#ffffff'},
});

export type PanelStyles = ReturnType<typeof makeStyles>;
